seed: 42

data:
  decouple_kv: true
  length: 256
  n_pairs: 2
  num_values: 64
  train_size: 512
  val_size: 64
  vocab_extra: 96

model:
  emb_dim: 64
  hid_dim: 128
  mem_dim: 256

memory:
  n_slots: 256
  k_top: 8

train:
  batch_size: 16
  lr: 0.002
  wd: 0.01
  epochs: 3
  lr_after_warm_factor: 0.5

emma:
  deq_max_iter: 6
  oracle_write: false
  warm_start_epochs: 2
  oracle_mix_ramp_epochs: 3
  oracle_mix_min: 0.3
  mem_into_deq: true
  mem_scale: 0.6
  mem_scale_min: 0.0
  logit_scale_max: 5.0
  nce_gate_write_cos: 0.15
  nce_gate_require_read: true
  nce_gate_read_patience: 1
  nce_lambda_pause_below_read: true
  read_cleanup_topk: 3
  enable_read_cleanup: true
  spectral_norm_keys: true

loss:
  lambda_pred_ce: 0.3
  lambda_write_cos: 0.2
  lambda_write_nce: 0.1

reg:
  addr_entropy_weight: 0.01

read:
  cleanup_mode: softmax
  cleanup_temp: 0.7
  sharpen_topk: 2
  sharpen_temp: 0.8
  sharpen_mask_margin: 5.0
